// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpeechRecognition.Infra.Context;

#nullable disable

namespace SpeechRecognition.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpeechRecognition.FileStorageDomain.FileStorageAggregate", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.ToTable("FileStorageAggregate");
                });

            modelBuilder.Entity("SpeechRecognition.FileStorageDomain.FileStorageAggregate", b =>
                {
                    b.OwnsMany("SpeechRecognition.FileStorageDomain.Entidades.AudioTranslation", "AudioTranslations", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)");

                            b1.Property<string>("FileStorageAggregateId")
                                .IsRequired()
                                .HasColumnType("character varying(36)");

                            b1.Property<string>("FileStorageConversionId")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)");

                            b1.Property<bool?>("IsApproved")
                                .HasColumnType("boolean");

                            b1.Property<bool>("IsSuccess")
                                .HasColumnType("boolean");

                            b1.Property<string>("Translation")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("TranslationTemplate")
                                .HasColumnType("integer");

                            b1.Property<int>("WhisperModel")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("FileStorageAggregateId");

                            b1.ToTable("AudioTranslation", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FileStorageAggregateId");
                        });

                    b.OwnsMany("SpeechRecognition.FileStorageDomain.Entidades.FileStorage", "FileStorages", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)");

                            b1.Property<string>("FileInfo")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("FileFullName");

                            b1.Property<string>("FileStorageAggregateId")
                                .IsRequired()
                                .HasColumnType("character varying(36)");

                            b1.Property<string>("OriginalFileName")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)");

                            b1.HasKey("Id");

                            b1.HasIndex("FileStorageAggregateId");

                            b1.ToTable("FileStorage", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FileStorageAggregateId");
                        });

                    b.OwnsMany("SpeechRecognition.FileStorageDomain.Entidades.FileStorageConversion", "FileStorageConversions", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)");

                            b1.Property<string>("FileStorageAggregateId")
                                .IsRequired()
                                .HasColumnType("character varying(36)");

                            b1.Property<string>("FileStorageId")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)");

                            b1.HasKey("Id");

                            b1.HasIndex("FileStorageAggregateId");

                            b1.ToTable("FileStorageConversion", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FileStorageAggregateId");
                        });

                    b.OwnsMany("SpeechRecognition.FileStorageDomain.Entidades.RabbitMqLog", "Logs", b1 =>
                        {
                            b1.Property<string>("Id")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("FileStorageAggregateId")
                                .IsRequired()
                                .HasColumnType("character varying(36)");

                            b1.Property<string>("Severity")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.HasKey("Id");

                            b1.HasIndex("FileStorageAggregateId");

                            b1.ToTable("RabbitMqLog", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FileStorageAggregateId");
                        });

                    b.Navigation("AudioTranslations");

                    b.Navigation("FileStorageConversions");

                    b.Navigation("FileStorages");

                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
